name: odat
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-171.0.dev <3.0.0'

dependencies:
  better_player: ^0.0.83
  constants: ^0.0.1
  dji: ^1.0.0-dev.23
  ffmpeg_kit_flutter_full_gpl: ^4.5.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  local_assets_server: ^2.0.2+12
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
